default_branch: develop
policies:
  main:
    environment: DEV
    gates: [gate1]
    include_tags: [main]
    disabled_gates: [gate2]
    commands:
      build: []
  develop:
    environment: DEV
    gates: [gate1]
    include_tags: [develop]
    disabled_gates: [gate2]
    commands:
      build: []
  test:
    environment: QA
    gates: [gate1, gate2]
    include_tags: [test]
    disabled_gates: []
    commands:
      build: []
  release:
    environment: PREPROD
    gates: [gate1, gate2]
    include_tags: [release]
    disabled_gates: []
    commands:
      build: []
